### ISSUE TITLE
`Encoding::UndefinedConversionError` in linux docker

### ISSUE THREAD

**Issue by jclifford-zd** [grosser/safe_regexp#1]
Looks like something to do with Marshal dumping binary data?
```
$ uname -a
Linux 694377e9f3a8 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 GNU/Linux
...
(dev)> require "safe_regexp"
=> true
(dev)> SafeRegexp.execute(/aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?/, :match?, "a")
Encoding::UndefinedConversionError: "\xB1" from ASCII-8BIT to UTF-8
        from /bundle/gems/safe_regexp-0.1.0/lib/safe_regexp.rb:16:in `write'
        from /bundle/gems/safe_regexp-0.1.0/lib/safe_regexp.rb:16:in `puts'
        from /bundle/gems/safe_regexp-0.1.0/lib/safe_regexp.rb:16:in `execute'
        from (irb):2
        from /bundle/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
        from /bundle/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
        from /bundle/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /bundle/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /bundle/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<main>'
        from /bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from /bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from bin/rails:21:in `<main>'
```
In local irb on osx it's fine:
```
$ uname -a
Darwin 19409-jclifford 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
...
irb(main):001:0> require 'safe_regexp'
=> true
irb(main):002:0> SafeRegexp.execute(/aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?aa?/, :match?, "a")
=> false
```

**Comment by jclifford-zd** [comment]
```
-        in_read, in_write = IO.pipe
-        out_read, out_write = IO.pipe
+        in_read, in_write = IO.pipe(binmode: true)
+        out_read, out_write = IO.pipe(binmode: true)
```
~Seems to fix in linux, will check in osx... not sure how to write tests for this~

Scratch that, it works fine in linux docker with no changes, just loading it as a local gem 🤕

**Comment by grosser** [comment]
please retry with latest version, if it still does not work I'll add the binmode

**Comment by grosser** [comment]
closing for now since I think that's taken care of when I switched to loading directly from the pipe

**Comment by jclifford-zd** [comment]
👍 works fine now
